aasisodiya/go

- email-service/README.md
- email-service/email-service-using-sendgrid/README.md
- email-service/email-service-using-sendgrid/main.go
- email-service/email-service-using-sendgrid/models/usertypes.go
- email-service/email-service-using-sendgrid/services/sendgrid.go
- email-service/email-service-using-ses/README.md
- email-service/email-service-using-ses/aws/ses.go
- email-service/email-service-using-ses/main.go
Sample code demonstrating use of **AWS SES and SendGrid**
> Feature: E-Mail Service in Golang

- golang-aws-lambda/README.md
- golang-postgres-basic-operations/README.md
Feature: Documentation Update for AWS Lambda
and Postgres
> Feature: Documentation Update

- golang-pluralsight-qa/README.md
> Feature: Pluralsight Quiz

- golang-private-package/README.md
> Feature: Document Update

- README.md
- golang-general/golang-data-types/README.md
- golang-general/golang-data-types/main.go
> Feature: Data Conversion

- README.md
- golang-postgres-basic-operations/README.md
- golang-postgres-basic-operations/sql-null-values/main.go
Feature: Handle Null Values Entry in DB
> Feature: Handle Null Values Entry in DB

- README.md
- golang-general/golang-execution-time/README.md
- golang-general/golang-execution-time/example/go.mod
- golang-general/golang-execution-time/example/main.go
- golang-general/golang-execution-time/example/service/demo.service.go
- golang-general/golang-execution-time/example/service/demo_test.go
Documentation: Execution Time in Go
> Documentation: Execution Time in Go

- README.md
- golang-simple-server/README.md
- golang-simple-server/main.go
Documentation: Golang Simple Server
> Documentation: Golang Simple Server

- README.md
- golang-general/golang-qna/README.md
Documentation: `go get` Command
> Documentation: `go get` Command

- README.md
- golang-aws-lambda/aws-lambda-custom/README.md
- golang-aws-lambda/aws-lambda-with-apigw/README.md
> Documentation: AWS Doc

- README.md
- golang-general/README.md
Documentation: `os.Exit()` Notes
> Documentation: `os.Exit()` Notes

- README.md
- golang-general/golang-basics/README.md
- golang-simple-server/README.md
> Documentation: Go Server

- README.md
- golang-general/golang-basics/README.md
> Documentation: Go Basics

- golang-general/golang-basics/README.md
> Documentation: Go Notes

- .gitignore
- golang-file-operations/README.md
- golang-file-operations/golang-find-file-with-extension/go.mod
- golang-file-operations/golang-find-file-with-extension/main.go
Feature: Find File With Extension Program
> Feature: Find File With Extension Program

- golang-file-operations/golang-get-file-metadata/go.mod
- golang-file-operations/golang-get-file-metadata/main.go
> Feature: Get File's Metadata

- README.md
- golang-aws-lambda/README.md
- golang-aws-operations/README.md
- golang-aws-operations/aws-dynamodb/README.md
- golang-aws-operations/aws-parameter-store/README.md
- golang-aws-operations/aws-s3/README.md
- golang-aws-operations/aws-s3/aws-s3-delete-object/README.md
- golang-aws-operations/aws-s3/aws-s3-delete-objects/README.md
- golang-aws-operations/aws-s3/aws-s3-get-object-(doesn't-work-as-exptected)/README.md
- golang-daemon-integration-with-configuration/README.md
- golang-email-service/README.md
- golang-email-service/email-service-using-sendgrid/README.md
- golang-email-service/email-service-using-ses/README.md
- golang-execute-commands/README.md
- golang-file-operations/README.md
- golang-general/README.md
- golang-general/golang-basics/README.md
- golang-general/golang-code-coverage/README.md
- golang-general/golang-data-types/README.md
- golang-general/golang-execution-time/README.md
- golang-general/golang-qna/README.md
- golang-memory-leaks/README.md
- golang-mysql-basic-operations/README.md
- golang-pluralsight-qa/README.md
- golang-postgres-basic-operations/README.md
- golang-private-package/README.md
- golang-simple-server/README.md
- Tracker Update
- Steps to handle error : `invalid version control suffix in github.com/ path`
> Documentation : Tracker Update

- golang-aws-lambda/README.md
- golang-aws-operations/README.md
- golang-aws-operations/aws-dynamodb/README.md
- golang-aws-operations/aws-parameter-store/README.md
- golang-aws-operations/aws-s3/README.md
- golang-aws-operations/aws-s3/aws-s3-delete-object/README.md
- golang-aws-operations/aws-s3/aws-s3-delete-objects/README.md
- golang-aws-operations/aws-s3/aws-s3-get-object-(doesn't-work-as-exptected)/README.md
- golang-daemon-integration-with-configuration/README.md
- golang-email-service/README.md
- golang-email-service/email-service-using-sendgrid/README.md
- golang-email-service/email-service-using-ses/README.md
- golang-execute-commands/README.md
- golang-file-operations/README.md
- golang-general/README.md
- golang-general/golang-basics/README.md
- golang-general/golang-code-coverage/README.md
- golang-general/golang-data-types/README.md
- golang-general/golang-execution-time/README.md
- golang-general/golang-qna/README.md
- golang-memory-leaks/README.md
- golang-mysql-basic-operations/README.md
- golang-pluralsight-qa/README.md
- golang-postgres-basic-operations/README.md
- golang-private-package/README.md
- golang-simple-server/README.md
> Documentation: Tracker Update

- golang-general/golang-basics/README.md
> Documentation: go vet command

- golang-general/golang-basics/README.md
Documentation: Steps to install `go` on EC2 machine
> Documentation: Steps to install `go` on EC2 machine

- golang-general/golang-basics/README.md
> Documentation: Go Commands

- golang-memory-leaks/README.md
Documentation: Update Memory Leak Description
Better explained the code lines causing the issues
> Documentation: Update Memory Leak Description

- README.md
- golang-general/golang-basics/README.md
[Documentation: Closure & Anonymous Function](https://github.com/aasisodiya/go/commit/21144d338b50438ba0d06849b9d1dd6b287466e7)
> Documentation: Closure & Anonymous Function

- README.md
- golang-general/golang-basics/README.md
- golang-godoc/demo.go
- golang-godoc/example_test.go
- golang-godoc/go.mod
> Documentation: Using `godoc`

- README.md
- golang-general/golang-basics/README.md
Documentation: Go Environment Variables
> Documentation: Go Environment Variables

- _config.yml
- _includes/head-custom-google-analytics.html
- _includes/head-custom.html
- assets/alogo.svg
- golang-godoc/README.md
> Theme: Update Theme Config

- golang-general/golang-basics/README.md
> Documentation: Go Routines

- README.md
- golang-general/unused-code/README.md
- golang-general/unused-code/go.mod
- golang-general/unused-code/main.go
- golang-general/unused-code/pkg1/go.mod
- golang-general/unused-code/pkg1/pkg1.go
- golang-general/unused-code/pkg2/go.mod
- golang-general/unused-code/pkg2/pkg2.go
Documentation: Identify Unused Code in Code
> Documentation: Identify Unused Code in Code

- golang-general/golang-code-coverage/README.md
Documentation: Code Coverage In Go Lang
- Correct the spelling
- Add more details
> Documentation: Code Coverage In Go Lang
